CourseMC/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import page_not_found_view

urlpatterns = [
    path('coursemc_control/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('CourseMC.ckeditor_urls')),
    path('api/v1/', include('api.urls')),
    path('', include('social_django.urls')),
    path('', include('Course.urls')),
    path('reviews/', include('reviews.urls')),
    path('questionnaire/', include('questionnaire.urls')),
    path('blog/', include('blog.urls')),
    path('interpreter/', include('py_interpreter.urls')),
    # path('chatgpt/', include('chatgpt.urls')),  # Не используется
    path('billing/', include('billing.urls')),
    path('todo/', include('todolist.urls')),
    path('certificate/', include('certificate.urls')),
    path('interview/', include('interview.urls')),
    path('code-review/', include('codereview.urls')),
    path('statistic/', include('statistic.urls')),
    path('<path:url>/', page_not_found_view),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns.append(path('<path:url>', page_not_found_view))

api/urls.py
from django.urls import path

from .views import (LearnGroupViewSet, ScheduleGet, ScheduleViewSet,
                    StudentQuestionView, StudentViewSet, ClassesTimetableView,
                    ApplicationsForTrainingView, PaymentAmountView,
                    MissingView,
                    ClassesTimetableGingerView, ProjectForReviewView)

urlpatterns = [
    path('schedule/', ScheduleViewSet.as_view()),
    path('schedule/get_by_username/', ScheduleGet.as_view()),
    path('student/', StudentViewSet.as_view()),
    path('groups/', LearnGroupViewSet.as_view()),
    path('student_question/', StudentQuestionView.as_view()),
    path('classes_timetable/<str:user_name>/', ClassesTimetableView.as_view()),
    path('app_training/', ApplicationsForTrainingView.as_view()),
    path('payment/<str:username>/', PaymentAmountView.as_view()),
    path('missing/', MissingView.as_view()),
    path('classes_timetable_ginger/<int:group>/',
         ClassesTimetableGingerView.as_view()),
    path('project_for_review/',
         ProjectForReviewView.as_view()),
]

questionnaire/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path("", index, name="questionnaireIndex"),
    path("create_poll/", create_poll, name="create_poll"),
    path("create_question/<int:quiz_id>", create_question, name="create_question"),
    path("create_answer/", create_answer, name="create_answer"),
    path("my_polls/", QuizListView.as_view(), name="my_poll"),
    path("go_poll/", go_poll, name="go_poll"),
    path("take_poll/<int:poll_id>", take_poll, name="take_poll"),
    path("rating/<int:poll_id>", rating, name="rating"),
]

questionnaire/models.py
from django.contrib.auth.models import User
from django.db import models


class Quiz(models.Model):
    title = models.CharField(max_length=64, verbose_name="Название")
    description = models.CharField(max_length=256, verbose_name="Описание")
    topic = models.CharField(max_length=64, verbose_name="Тема")
    lifetime = models.DateTimeField(verbose_name="Действует до")
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Пользователь",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")

    def __str__(self):
        return f"{self.title}, {self.topic}"

    class Meta:
        verbose_name = "Опрос"
        verbose_name_plural = "Опросы"


class Question(models.Model):
    question = models.CharField(max_length=64, verbose_name="Вопрос")
    quiz = models.ForeignKey(
        "Quiz", on_delete=models.CASCADE, verbose_name="Опрос", related_name="questions"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")

    def __str__(self):
        return f"{self.question}"

    class Meta:
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"


class AnswerQuestion(models.Model):
    answer = models.CharField(max_length=256, verbose_name="Ответ")
    question = models.ForeignKey(
        "Question",
        on_delete=models.CASCADE,
        verbose_name="Вопрос",
        related_name="answers",
    )
    correct = models.BooleanField(default=False, verbose_name="Это правильный ответ?")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")

    def __str__(self):
        return f"{self.answer}"

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"


class UserAnswer(models.Model):
    quiz = models.ForeignKey(
        "Quiz",
        on_delete=models.CASCADE,
        verbose_name="Опрос",
        related_name="user_quiz",
        null=True,
    )
    question = models.ForeignKey(
        "Question",
        on_delete=models.CASCADE,
        verbose_name="Вопрос",
        related_name="user_question",
        null=True,
    )
    answers = models.ForeignKey(
        "AnswerQuestion",
        on_delete=models.CASCADE,
        verbose_name="Ответ",
        related_name="user_answer",
        null=True,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Пользователь",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")

    class Meta:
        verbose_name = "Ответ пользователя"
        verbose_name_plural = "Ответы пользователей"


class PassedPolls(models.Model):
    quiz = models.ForeignKey(
        "Quiz",
        on_delete=models.CASCADE,
        verbose_name="Опрос",
        related_name="passed_quiz",
    )
    passed_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Пользователь",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Закончил опрос")

    def __str__(self):
        return f"{self.quiz}, {self.passed_user}"

    class Meta:
        verbose_name = "Пройденный опрос"
        verbose_name_plural = "Пройденные опросы"


class Rating(models.Model):
    answer_number = models.IntegerField(verbose_name="Число звёзд")
    comment = models.CharField(
        max_length=750,
        blank=True,
        default="Комментарий не добавлен!",
        verbose_name="Комментарий",
    )
    quiz = models.ForeignKey(
        "Quiz", on_delete=models.CASCADE, verbose_name="Опрос", related_name="rating"
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Пользователь",
    )

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинг"

    def __str__(self):
        return f"{self.quiz}, {self.answer_number} звёзд. {self.comment}"

questionnaire/forms.py
from django.forms import DateTimeInput, ModelForm, Select
from django.http import QueryDict

from .models import *


class DateTimeInput(DateTimeInput):
    input_type = "datetime-local"


class QuizForm(ModelForm):
    class Meta:
        model = Quiz
        fields = (
            "title",
            "description",
            "topic",
            "lifetime",
        )
        widgets = {
            "lifetime": DateTimeInput(),
        }


class QuestionForm(ModelForm):
    def __init__(self, quiz, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["quiz"].empty_label = "Не выбрано!"

        if quiz is not None:
            if isinstance(quiz, QueryDict):
                qs = Quiz.objects.filter(pk=quiz["quiz"]).all()
            else:
                qs = Quiz.objects.filter(pk=quiz[0].pk).all()
            self.initial["quiz"] = qs[0].pk
            self.fields["quiz"].queryset = qs

    class Meta:
        model = Question
        fields = (
            "question",
            "quiz",
        )
        widgets = {
            "quiz": Select(attrs={"class": "form-control"}),
        }


class AnswerForm(ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        quiz = Quiz.objects.filter(user=user).last()
        self.fields["question"].empty_label = "Не выбрано!"
        self.fields["question"].queryset = self.fields["question"].queryset.filter(quiz=quiz).order_by(
            "-pk"
        )

    class Meta:
        model = AnswerQuestion
        fields = (
            "answer",
            "question",
            "correct",
        )
        widgets = {
            "question": Select(
                attrs={"class": "form-control", "placeholder": "Не выбрано!"}
            ),
        }

questionnaire/views.py
from typing import Union

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import (HttpResponseNotFound)
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView

from .forms import AnswerForm, QuestionForm, QuizForm
from .models import (AnswerQuestion, PassedPolls, Question, Quiz, Rating,
                     UserAnswer)
from .service import process_form, _check_poll_lifetime, get_standart_render


class QuizListView(ListView):
    model = Quiz
    template_name = "questionnaire/my_poll.html"
    context_object_name = "my_polls"
    paginate_by = 16

    def get_queryset(self):
        if self.request.user.is_authenticated:
            my_polls = (
                Quiz.objects.filter(user=self.request.user)
                .order_by("-created_at")
                .prefetch_related()
            )
            return my_polls

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["UserAnswer"] = UserAnswer
        context["PassedPolls"] = PassedPolls

        return context

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("account_login")
        if request.method.lower() in self.http_method_names:
            handler = getattr(
                self, request.method.lower(), self.http_method_not_allowed
            )
        else:
            handler = self.http_method_not_allowed
        return handler(request, *args, **kwargs)


def index(request):
    return render(request, "questionnaire/index.html")


@login_required
def create_poll(request):
    if request.method == "GET":
        context = {"form": QuizForm()}
        return render(request, "questionnaire/create_poll.html", context)
    form = QuizForm(request.POST)
    if form.is_valid():
        form_with_user = form.save(commit=False)
        form_with_user.user = request.user
        form_with_user.save()
        messages.success(request, "Вы успешно создали опрос!")
        return redirect("create_question", form_with_user.pk)
    messages.error(request, "Хм, что-то не то!")
    return redirect("create_poll")


@login_required
def create_question(request, quiz_id):
    quiz = Quiz.objects.filter(pk=quiz_id).all()
    if request.method == "GET":
        context = {
            "form": QuestionForm(quiz),
        }
        return render(request, "questionnaire/create_question.html", context)
    form = QuestionForm(None, request.POST)
    return process_form(request, form, quiz_id)


@login_required
def create_answer(request):
    if request.method == "GET":
        context = {"form": AnswerForm(user=request.user)}
        return render(request, "questionnaire/create_answer.html", context)
    form = AnswerForm(request.user, request.POST)
    return process_form(
        request,
        form,
        message_success="Вы создали ответ на вопрос!",
        func_redirect="create_answer",
    )


@login_required
def my_poll(request):
    my_polls = (
        Quiz.objects.filter(user=request.user)
        .order_by("-created_at")
        .prefetch_related()
    )
    context = {
        "my_polls": my_polls,
        "UserAnswer": UserAnswer,
        "PassedPolls": PassedPolls,
    }
    return render(request, "questionnaire/my_poll.html", context)


@login_required
def go_poll(request):
    if request.method == "GET":
        return render(request, "questionnaire/go_poll.html")
    if not request.POST.get("poll_id") or not request.POST.get(
            "poll_id").isdigit():
        messages.error(request, "Значение поля id опроса не корректно!")
        return render(request, "questionnaire/go_poll.html")
    return redirect("take_poll", request.POST.get("poll_id"))


@login_required
def take_poll(request, poll_id):
    try:
        poll = Quiz.objects.get(pk=poll_id)
    except Quiz.DoesNotExist:
        messages.error(request, "Вы указали не верный id опроса!")
        return redirect("go_poll")
    question = check_possibility_passing_poll(request, poll)
    if isinstance(question, HttpResponseNotFound):
        return question
    if request.method == "GET":
        return get_standart_render(request, poll, question)
    number_question = request.POST.get("number_question")
    answers = request.POST.get("answers")

    all_question = poll.questions.all()
    # Обрабатываем кнопку "Назад". Если нажата, возвращаем предыдущий вопрос
    if request.POST.get("redirect") and number_question:
        question = all_question.filter(pk=int(number_question)).first()
        return get_standart_render(request, poll, question)

    if not (number_question and answers):
        messages.error(request, "Вы передали не все параметры!")
        return get_standart_render(request, poll, question)

    for i in request.POST.lists():
        answers = (
            i[1] if i[0] == "answers" else []
        )  # Получаем ответ, который дал пользователь
    try:
        UserAnswer.objects.get(
            quiz=poll,
            question=get_object_or_404(Question, pk=int(number_question)),
            user=request.user,
        ).delete()
    except:
        pass
    answer = UserAnswer(
        quiz=poll,
        question=get_object_or_404(Question, pk=int(number_question)),
        answers=AnswerQuestion.objects.filter(pk=int(answers[0]))[0],
        user=request.user,
    )
    answer.save()

    number_iter = 1
    while True:
        question = all_question.filter(
            pk=int(number_question) + number_iter).first()

        # Проверяем, есть ли вопрос, если нет, то сообщаем об успешном прохождении опроса
        if not question:
            passed_quiz = PassedPolls(quiz=poll, passed_user=request.user)
            passed_quiz.save()
            messages.info(request, "Вы успешно прошли опрос!")
            return redirect("rating", poll_id)
        if not question.answers.all():
            number_iter += 1
            continue
        break
    return get_standart_render(request, poll, question)


@login_required
def rating(request, poll_id: int):
    quiz = Quiz.objects.filter(pk=poll_id).first()
    if not quiz or not PassedPolls.objects.filter(
            passed_user=request.user).first():
        return HttpResponseNotFound(
            "Указанный опрос не найден или вы его не прошли!")
    if request.method == "POST":
        try:
            rating_quiz = Rating.objects.get(user=request.user, quiz=quiz)
            rating_quiz.delete()
            rating_quiz = Rating(
                answer_number=request.POST.get("rating"),
                comment=request.POST.get("comment"),
                quiz=quiz,
                user=request.user,
            )
            rating_quiz.save()
            messages.success(request, "Вы успешно оставили отзыв!")
        except:
            pass
        finally:
            return redirect("questionnaireIndex")
    context = {"poll": quiz}
    return render(request, "questionnaire/rating.html", context)


def check_possibility_passing_poll(
        request, poll: Quiz
) -> Union[Question, HttpResponseNotFound]:
    """
    Используется для проверки возможности пройти определённый опрос пользователем.
    request: WSGIRequest
    return: Question (вопрос на который пользователь будет отвечать)
            or HttpResponseNotFound (сообщение о невозможности пройти опрос).
    """
    check_poll_lifetime = _check_poll_lifetime(poll)
    if not isinstance(check_poll_lifetime, bool):
        return check_poll_lifetime
    if PassedPolls.objects.filter(quiz=poll, passed_user=request.user):
        return HttpResponseNotFound("Вы уже прошли этот опрос!")
    for question in poll.questions.all():
        if len(question.answers.all()) > 0:
            return question
    return HttpResponseNotFound("В этом опросе нет вопросов с ответами")

questionnaire/templates/questionnaire/create_answer.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{% block header %}
    <title>Добавить вопрос - YourQuestionnaire</title>
    {% include "questionnaire/includes/header.html" %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}
{% block content %}

    <form class="decor" method="post" action="{% url 'create_answer' %}">
        <div class="form-left-decoration"></div>
        <div class="form-right-decoration"></div>
        <div class="circle"></div>
        <div class="form-inner">
            <h3>Добавить ответ</h3>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить">
            <center><a href="{% url 'questionnaireIndex' %}"><small>Завершить добавление ответов</small></a></center>
        </div>
    </form>

    </div>
{% endblock %}

questionnaire/templates/questionnaire/create_poll.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{#{% block header %}{% endblock %}#}
{% block content %}
    <title>Создать опрос - YourQuestionnaire</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <form class="decor" method="post" action="{% url 'create_poll' %}">
        <div class="form-left-decoration"></div>
        <div class="form-right-decoration"></div>
        <div class="circle"></div>
        <div class="form-inner">
            <h3>Создать опрос</h3>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Создать">
        </div>
    </form>

    </div>
{% endblock %}

questionnaire/templates/questionnaire/create_question.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{% block content %}
    <style>
    label[for='id_quiz']{
        display: none;
    }
    #id_quiz{
        display: none;
    }
    </style>
    <title>Добавить вопрос - YourQuestionnaire</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <form class="decor" method="post">
        <div class="form-left-decoration"></div>
        <div class="form-right-decoration"></div>
        <div class="circle"></div>
        <div class="form-inner">
            <h3>Добавить вопрос</h3>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить">
            <center><a href="{% url 'create_answer' %}"><small>Завершить добавление вопросов</small></a></center>
        </div>
    </form>

    </div>
{% endblock %}

questionnaire/templates/questionnaire/go_poll.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{% block content %}
    <title>Пройти опрос - YourQuestionnaire</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <form class="decor" method="post" action="{% url 'go_poll' %}">
        <div class="form-left-decoration"></div>
        <div class="form-right-decoration"></div>
        <div class="circle"></div>
        <div class="form-inner">
            <h3>Пройти опрос</h3>
            {% csrf_token %}
            <br>
            <label>Введите id опроса:</label>
                <input oninput="this.value = this.value.replace(/[^0-9]/g, '');" type="text" placeholder="Введите id опроса" name="poll_id" required>
            <input type="submit" value="Перейти">
        </div>
    </form>

    </div>
{% endblock %}

questionnaire/templates/questionnaire/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Твой опросник</title>
	<link rel="stylesheet" href="{% static 'Course/css/style.css' %}">
	<link rel="shortcut icon" href="{% static 'Course/assets/favicon.ico' %}" type="image/x-icon">
</head>
<style>
    html,
    body {
        max-width: 100%;
        /* overflow-x: hidden; */
    }
</style>

<body onclick="closeAll()">
	{% include 'template/header.html' %}

<section class="scheduleSection">
    <h2><span>Твой</span> опросник</h2>

    <div class="box">
        <div class="imageBox">
            <img src="{% static 'Course/assets/6.png' %}" alt="">
            <img src="{% static 'Course/assets/7.png' %}" alt="">
        </div>

        <div class="contentBox">
            <div class="top">
                <h3>Как создать опрос</h3>
                <p>Составить интересную анкету, заполнить которую будет не в тягость, а в радость, довольно просто.
                    Но нужно знать несколько основных правил:</p>
            </div>

            <div class="stepline">
                <div class="line"></div>

                <div class="step">
                    <div>1</div>
                    <p>Определитесь с целью анкеты. Сфокусируйтесь на одной конкретной цели. Так вы сможете собрать
                        релевантную информацию и не запутать пользователя.</p>
                </div>
                <div class="step">
                    <div>2</div>
                    <p>Поймите, какую информацию собирать. Как только станет понятна цель, выберете, какие именно
                        данные и в каком формате собирать.</p>
                </div>
                <div class="step">
                    <div>3</div>
                    <p>Будьте объективны. Убедитесь, что задаёте только прямые вопросы, избегая наводящих
                        конструкций. Некоторые слова — такие, как «запретить» могут повлиять на результат вопроса. К
                        примеру, вопрос «Мы получаем множество положительных отзывов от наших счастливых клиентов.
                        Как вы считаете, на сколько хорош наш сервис?» — пример того, как вопрос подталкивает
                        отвечающего быть более благосклонным к вашей компании. Попробуйте попросить «Оцените
                        удобство нашего сервиса по 5-балльной шкале» и предложите эту шкалу. И ещё. Не позволяйте
                        себе строить догадки и включать их в вопросы.</p>
                </div>
                <div class="step">
                    <div>4</div>
                    <p>Следите за порядком вопросов. Логичная последовательность вопросов важна, как для вас, так и
                        для проходящего опрос. Самый оптимальный вариант — «от общего к частному».</p>
                </div>
                <div class="step">
                    <div>5</div>
                    <p>Избегайте двойных вопросов. Один блок — один вопрос. Иначе вы получите искажённую информацию.
                    </p>
                </div>
                <div class="step">
                    <div>6</div>
                    <p>Пишите простым языком. В опросниках не стоит использовать жаргон и сложные обороты. Сделайте
                        свою анкету простой и понятной и тогда каждый респондент наверняка дойдёт до финального
                        вопроса.</p>
                </div>
                <div class="step">
                    <div>7</div>
                    <p>Протестируйте опросник. Пришлите готовую анкету друзьям и коллегам, чтобы ещё раз проверить
                        логику опроса и разглядеть возможные ошибки.</p>
                </div>
            </div>
        </div>
    </div>
</section>
    {% if user.is_authenticated %}
        <button style='background: #FF977E;margin-left: 30%; display: inline;' class="quizButton" onclick="document.location=`{% url 'go_poll' %}`">Пройти опрос</button>
        <button style='background: #FF977E;margin-left: 25px; display: inline;' class="quizButton" onclick="document.location=`{% url 'create_poll' %}`">Создать опрос</button>
        <button style='background: #FF977E;margin-left: 25px; display: inline;' class="quizButton" onclick="document.location=`{% url 'my_poll' %}`">Мои опросы</button>
    {% endif %}

{% include 'template/footer.html' %}
</body>

</html>

questionnaire/templates/questionnaire/rating.html
{% extends 'questionnaire/template/base.html' %}
{% load static %}
{% load questionnaire_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/rating.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/dynamic_background.css' %}">
{% endblock %}

{% block content %}

    <style>

        /* Styling the Body element i.e. Color,
        Font, Alignment */
        body {
            font-family: Verdana;
            text-align: center;
        }

        /* Styling the Form (Color, Padding, Shadow) */
        aside {
            background-color: #fff;
            max-width: 500px;
            margin: 50px auto;
            padding: 30px 20px;
            box-shadow: 2px 5px 10px rgba(110, 0, 0, 0.5);
        }

        /* Styling form-control Class */
        .form-control {
            text-align: left;
            margin-bottom: 25px;
        }

        /* Styling form-control Label */
        .form-control label {
            display: block;
            margin-bottom: 10px;
        }

        /* Styling form-control input,
        select, textarea */
        .form-control input,
        .form-control select,
        .form-control textarea {
            border: 1px solid #777;
            border-radius: 2px;
            font-family: inherit;
            padding: 10px;
            display: block;
            width: 95%;
        }

        /* Styling form-control Radio
        button and Checkbox */
        .form-control input[type="radio"],
        .form-control input[type="checkbox"] {
            display: inline-block;
            width: auto;
        }

        /* Styling Button */
        button {
            background-color: #05c46b;
            border: 1px solid #777;
            border-radius: 2px;
            font-family: inherit;
            font-size: 21px;
            display: block;
            width: 100%;
            margin-top: 50px;
            margin-bottom: 20px;
        }

        .btn-link {
            border: none;
            outline: none;
            background: none;
            cursor: pointer;
            color: #0000EE;
            padding: 0;
            margin: 0;
            text-decoration: none;
            font-family: inherit;
            font-size: inherit;
            width: auto;
            height: auto;
        }
    </style>

    <div style="height: 85vh;">
        {% include 'questionnaire/includes/flash_messages.html' %}

        <aside>
            <form id="form" method="post">

                {% csrf_token %}

                <div class="rating">

                    <input type="radio" id="star-1" name="rating" value="5">
                    <label for="star-1" title="Оценка «5»"></label>

                    <input type="radio" id="star-2" name="rating" value="4">
                    <label for="star-2" title="Оценка «4»"></label>

                    <input type="radio" id="star-3" name="rating" value="3">
                    <label for="star-3" title="Оценка «3»"></label>

                    <input type="radio" id="star-4" name="rating" value="2">
                    <label for="star-4" title="Оценка «2»"></label>

                    <input type="radio" id="star-5" name="rating" value="1">
                    <label for="star-5" title="Оценка «1»"></label>
                    <span>Оценка: </span>
                </div>

                <div class="form-control border-0">

                    <div class="form-control border-0">
                        <label for="inp-1">
                            <span>Ваш комментарий:</span>
                            <textarea class="form-control" rows="5" maxlength="1000"
                                      placeholder="Максимум 750 символов..." name="comment"></textarea>
                        </label>
                    </div>

                    <button type="submit" value="submit">
                        Сохранить отзыв
                    </button>
                </div>
            </form>
        </aside>
    </div>


{% endblock %}